name: Vercel Production Deployment
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  issues: write
  deployments: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
          
      - name: Set Preview URL
        run: |
          echo "PREVIEW_URL=${{ steps.deploy.outputs.preview-url }}" >> $GITHUB_ENV
          
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            ✨ Vercel Preview Deployment is ready!
            Preview: ${{ env.PREVIEW_URL }}
          comment_tag: deployment
          
      - name: Handle Errors
        if: failure()
        run: |
          echo "Deployment failed. Check the logs for more information."
          exit 1